// <auto-generated />
using System;
using KorpTeste.BillingService.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace KorpTeste.BillingService.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(BillingDbContext))]
    [Migration("20260902022053_AdicionarMetadadosProcessamentoNota")]
    partial class AdicionarMetadadosProcessamentoNota
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.HasSequence("nota_fiscal_numero_seq");

            modelBuilder.Entity("KorpTeste.BillingService.Domain.Entities.ItemNotaFiscal", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("CodigoProduto")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("codigo_produto");

                    b.Property<string>("DescricaoProduto")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("descricao_produto");

                    b.Property<Guid>("NotaFiscalId")
                        .HasColumnType("uuid")
                        .HasColumnName("nota_fiscal_id");

                    b.Property<Guid>("ProdutoId")
                        .HasColumnType("uuid")
                        .HasColumnName("produto_id");

                    b.Property<int>("Quantidade")
                        .HasColumnType("integer")
                        .HasColumnName("quantidade");

                    b.HasKey("Id");

                    b.HasIndex("NotaFiscalId");

                    b.HasIndex("NotaFiscalId", "ProdutoId")
                        .IsUnique();

                    b.ToTable("itens_nota_fiscal", null, t =>
                        {
                            t.HasCheckConstraint("ck_itens_nota_fiscal_quantidade_positiva", "quantidade > 0");
                        });
                });

            modelBuilder.Entity("KorpTeste.BillingService.Domain.Entities.NotaFiscal", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("CaminhoArquivo")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("caminho_arquivo");

                    b.Property<DateTimeOffset>("CriadaEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("criada_em");

                    b.Property<DateTimeOffset?>("FechadaEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fechada_em");

                    b.Property<DateTimeOffset?>("GeradaEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("gerada_em");

                    b.Property<string>("NomeArquivo")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("nome_arquivo");

                    b.Property<long>("Numero")
                        .HasColumnType("bigint")
                        .HasColumnName("numero");

                    b.Property<bool>("ProcessamentoEmAndamento")
                        .HasColumnType("boolean")
                        .HasColumnName("processamento_em_andamento");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<int>("Versao")
                        .IsConcurrencyToken()
                        .HasColumnType("integer")
                        .HasColumnName("versao");

                    b.HasKey("Id");

                    b.HasIndex("Numero")
                        .IsUnique();

                    b.ToTable("notas_fiscais", null, t =>
                        {
                            t.HasCheckConstraint("ck_notas_fiscais_numero_positivo", "numero > 0");

                            t.HasCheckConstraint("ck_notas_fiscais_status_valido", "status IN ('Aberta', 'Fechada')");
                        });
                });

            modelBuilder.Entity("KorpTeste.BillingService.Domain.Entities.ItemNotaFiscal", b =>
                {
                    b.HasOne("KorpTeste.BillingService.Domain.Entities.NotaFiscal", "NotaFiscal")
                        .WithMany("Itens")
                        .HasForeignKey("NotaFiscalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NotaFiscal");
                });

            modelBuilder.Entity("KorpTeste.BillingService.Domain.Entities.NotaFiscal", b =>
                {
                    b.Navigation("Itens");
                });
#pragma warning restore 612, 618
        }
    }
}
